config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  resources :users do
  resources :posts do
  resources :comments
  resources :likes, only: [:create]
    end
  end

get '/api/users/:user_id/posts', to: 'api#index_posts'
get '/api/users/:user_id/posts/:post_id/comments', to: 'api#post_comments'
post '/api/users/:user_id/posts/:post_id/comment', to: 'api#create_comments'


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    user ||= User.new
    if user.is? :admin
      can :manage, :all
    elsif can :manage, Post, author_id: user.id
      can :manage, Comment, author_id: user.id
      can :read, :all
    else
      can :read, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_create :update_comments_counter

  def update_comments_counter
    post.update(comments_counter: post.comments.length)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_create :update_likes_counter

  # private

  def update_likes_counter
    post.update(likes_counter: post.likes.length)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  after_save :update_posts_counter
  after_destroy :update_posts_counter

  # private

  def update_posts_counter
    author.update(posts_counter: author.posts.length)
  end

  def most_recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, presence: true, numericality: { only_integer: true }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable
  has_many :posts, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'

  ROLES = %i[admin default].freeze

  def is?(requested_role)
    role == requested_role.to_s
  end

  def most_recent_posts
    posts.order(created_at: :asc).limit(3)
  end

  validates :name, presence: true, length: { minimum: 2 }, uniqueness: true
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  protect_from_forgery with: :null_session

  def index_posts
    render json: Post.all
  end

  def post_comments
    render json: Comment.where(post_id: params[:post_id])
  end

  def create_comments
    @comment = Comment.new(comment_params)
    @comment.post_id = params[:post_id]
    @comment.author_id = params[:user_id]

    if @comment.save
      render json: { status: 201, message: 'Comment creation success!', content: { comment: @comment } }
    else
      render json: @comment.errors, status: :bad_request, message: 'Failed!'
    end

    # data = JSON.parse(request.raw_post)
    # @comment = Comment.create(post_id: data['post_id'], user_id: data['user_id'], text: data['text'])

    # if @comment.save
    #   render json: 'Comment created successfully'
    # else
    #   render json: 'Comment not created'
    # end
  end

  private

  def comment_params
    params.permit(:text)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
  protect_from_forgery unless: request.format.json?
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :surname, :email, :password, :current_password)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @current_user = User.find(params[:user_id])

    @comment = Comment.new
  end

  def create
    @user = User.find(params[:user_id])
    @post = Post.find(params[:post_id])
    @comment = Comment.create(post: @post, author: @user, text: params[:comment][:text])

    if @comment.valid?
      @comment.save
      flash.notice = 'Comment added successfuly.'
      redirect_to user_post_path(@user.id, @post.id)
    else
      flash.alert = 'Please try again.'
      redirect_to new_user_post_comment_path(@user.id, @post.id)
    end
  end

  def post_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @current_user = User.find(params[:user_id])
    @user_id = params[:user_id]
    @post_id = params[:post_id]
    if liked?
      flash.notice = 'Like added successfuly.'
      return
    else
      Like.create(author_id: @current_user.id, post_id: @post_id)
    end
    redirect_to user_post_path(@user_id, @post_id)
  end

  private

  def liked?
    Like.find_by(author_id: @current_user.id, post_id: @post_id).present?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # before_action :authenticate_user!

  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments)
    @post_id = params[:id]
  end

  def show
    @user = User.find(params[:user_id])

    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @current_user = User.find(params[:user_id])
    post = Post.new(post_params.merge(author_id: @current_user.id, comments_counter: 0, likes_counter: 0))
    if post.valid?
      post.save
      flash.notice = 'Post added successfuly.'
    else
      flash.alert = "Couldn't add the post."
    end
    redirect_to user_path(@current_user.id)
  end

  def destroy
    @current_user = current_user
    @user = User.find_by(id: params[:user_id])
    @post = @user.posts.find_by(id: params[:id])
    @post.destroy
    redirect_to user_posts_path(@user.id), success: 'Post was successfully deleted'
  end

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :authenticate_user!
  def index
    @users = User.order(:id)
  end

  def show
    @user = current_user
    # @posts = @user.most_recent_posts
    @post = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
    <h2> Comments</h2>

<%= form_with model: @comment, url: user_post_comments_path do |f| %>

     <div>

      <%= f.label :text, "Text" %>
      <%= f.text_area :text, required: true %>
    </div>
    <%= f.submit "Publish"%>

  </div>
  
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

       <% if user_signed_in? %>
       <div class="logout">

       <%=button_to "logout", destroy_user_session_path, method: :delete  %>
       </div>
       <%end%>
       
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<h1>Posts</h1>

<div class="usersShow">
<%= link_to 'Create a post' ,new_user_post_path(@user, @post)%>

    <div><%= image_tag (@user.photo) unless @user.photo.nil? %></div>
            <h1><%=@user.name%></h1>
            <button class="counter">Number of posts: <%= @user.posts_counter%></button>
            </div>
            
            <%@posts.each do |post|%>

              <% if can? :destroy, post %> <%= button_to "Delete", user_post_path(post.author_id, post.id), method: :delete %>
               <%end%>

                <div class="likeButton">
                
                <p class="likes"><%= link_to (post.title),"/users/#{@user.id}/posts/#{post.id}"%></p>
                <p><%=post.text%></p>
                 <p><%= "Comments: #{post.comments_counter || 0}, Likes: #{post.likes_counter || 0 }" %></p>
                </div>

                <%post.most_recent_comments.each do |comment|%>
                <p><%= "#{comment.author.name}: #{comment.text}" %></p>

                <%end%>

              <%end%>

app/views/posts/new.html.erb
<h1>New</h1>

<%= form_with model: @post, url: user_posts_path do |f| %>
  <% flash.each do |type, msg| %>
    <div class="comment">
      <%= msg %>
    </div>
  <% end %>
    <div>
    
      <%= f.label :title, "Title" %>
      <%= f.text_field :title %>
</div>
     <div>
      <%= f.label :text, "Text" %>
      <%= f.text_area :text %>
    </div>
    <%= f.submit "Publish"%>
  </div>
<% end %>

app/views/posts/show.html.erb
<h1>Words of Light</h1>
<div>
<h1 ><%= @post.title %>  by:<%=@post.author.name%></h1>
<p ><%= @post.text %>  by:<%=@post.author.name%></p>
<p><%= "Comments: #{@post.comments_counter || 0}, Likes: #{@post.likes_counter || 0 }" %></p>
   <% flash.each do |type, msg| %>
      <div class="comment">
        <%= msg %>
      </div>
    <% end %>
<% @post.comments.each do |comment| %>
    <p><%= "#{comment.author.name}: #{comment.text}" %></p>

  <% end %>

  <button><%= link_to ("New post"), new_user_post_path(@user.id, @post.id)%></button>



  <button> <%= link_to 'Add a comment',new_user_post_comment_path(@user.id ,@post.id)%>
  </button>

  <%= button_to 'Like',user_post_likes_path(@user.id, @post.id), method: :post,class:"btn btn-light mt-3"%>

</div>

app/views/users/index.html.erb
<h1 class= "title">The Light Box</h1>
    <main class= "main">
    <ul>

    <% @users.each do |user| %>

        <li class="grow">
    <%
=begin%>
 <div><%= image_tag (user.photo), height: 200 ,width: 200 %></div> 
<%
=end%>

<%= image_tag (user.photo) unless user.photo.nil? %>
    <button class="counter"><%= link_to (user.name),user_path(user.id) %></button>
            <h2>Number of posts: <%= user.posts_counter%></h2>

            <%end%>
            </li>
    </ul>
    
    </main>

app/views/users/show.html.erb
<h1>Lighters</h1>
<section>
<div>
<h1>
<div class="usersShow">
    <div><%= image_tag (@post.photo) unless @post.photo.nil? %></div>
    <div><%= link_to (@post.name),user_path(@post.id) %></div>
            <button class="counter">Number of posts: <%= @post.posts_counter%></button>
            </div>
</h1>
<p><%= @post.bio%></p>
<%@post.most_recent_posts.each do |post|%>
    <div>
    <%= link_to (post.title),user_post_path(@post.id) %>

    <p><%=post.text%></p>
     <p><%= "Comments: #{post.comments_counter || 0}, Likes: #{post.likes_counter || 0 }" %></p>
    </div>
    <%end%>
    <button class="allPosts counter"><%= link_to ("See all posts"),user_posts_path(@post.id) %></button>

</div>
</section>